setup: 
  - CMD, VARIBLE, PACKAGE NAME, or DATA
  - {package: mysql, version: 8.0}
  - apt-get install mysql -y
  - java11, nodejs, wget
  - URL=https://github.ncsu.edu/engr-csc326-staff/iTrust2-v10
  - ...

jobs:
  - name: build-itrust
    steps: 
      - name: apt update
        run: sudo apt update

      - name: apt install
        run: sudo apt install -y openjdk-11-jre-headless maven mysql-server git

      - name: git clone
        run: git clone https://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@github.ncsu.edu/engr-csc326-staff/iTrust2-v10 iTrust2

      - name: step name
        run: cd iTrust2/iTrust2 && mvn --batch-mode --update-snapshots clean test

      