setup: 
  - CMD, VARIBLE, PACKAGE NAME, or DATA
  - {package: mysql, version: 8.0}
  - apt-get install mysql -y
  - java11, nodejs, wget
  - URL=https://github.ncsu.edu/engr-csc326-staff/iTrust2-v10
  - ...

jobs:
  - name: itrust-build
    steps: 
      - name: apt remove unattended-upgrades
        run: sudo apt -y remove unattended-upgrades

      - name: apt update
        run: sudo apt update

      - name: apt install
        run: sudo apt install -y openjdk-11-jre-headless maven mysql-server git

      - name: git clone Windows
        run: git clone https://%GITHUB_ACCESS_TOKEN%@github.ncsu.edu/engr-csc326-staff/iTrust2-v10 iTrust2

      - name: git clone Mac
        run: git clone https://${GITHUB_ACCESS_TOKEN}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10 iTrust2

      - name: start mysql
        run: sudo systemctl enable --now mysql

      - name: create mysql account
        run: sudo mysql -e \"CREATE USER admin@'%' IDENTIFIED BY 'admin'\"

      - name: grant access to mysql account
        run: sudo mysql -e \"GRANT ALL PRIVILEGES ON *.* TO admin@'%'\"

      - name: flush mysql databases
        run: sudo mysql -e \"FLUSH PRIVILEGES\"

      - name: create application.yml
        run: cp iTrust2/iTrust2/src/main/resources/application.yml.template iTrust2/iTrust2/src/main/resources/application.yml

      - name: update mysql username in application.yml
        run: sed -i 's/username.*/username:\ admin/g' iTrust2/iTrust2/src/main/resources/application.yml

      - name: update mysql password in application.yml
        run: sed -i 's/password.*/password:\ admin/g' iTrust2/iTrust2/src/main/resources/application.yml

      - name: update mysql hostname in application.yml
        run: sed -i 's/localhost/database/g' iTrust2/iTrust2/src/main/resources/application.yml

      - name: update hosts file
        run: echo '127.0.0.1 database' | sudo tee -a /etc/hosts

      - name: build iTrust2
        run: mvn -f iTrust2/iTrust2/pom.xml --batch-mode --update-snapshots clean test

      - name: package iTrust2
        run: mvn -f iTrust2/iTrust2/pom.xml package war:war

      - name: copy iTrust2 archive
        run: cp iTrust2/iTrust2/target/iTrust2-10.jar /bakerx/tmp/

  - name: mutation-coverage
    mutation:
      url: https://github.com/chrisparnin/checkbox.io-micro-preview.git
      iterations: 1000
      snapshots:
       - http://localhost:3000/survey/long.md
       - http://localhost:3000/survey/upload.md
       - http://localhost:3000/survey/survey.md
       - http://localhost:3000/survey/variations.md
       
    steps:
      - name: apt remove unattended-upgrades
        run: sudo apt -y remove unattended-upgrades

      - name: apt update
        run: sudo apt update

      - name: apt install
        run: sudo apt install -y git npm libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libxdamage-dev libgbm-dev libpangocairo-1.0-0 net-tools

      - name: git clone screenshot 
        run: git clone https://github.com/ruttabega/screenshot.git

      - name: npm install and link screenshot
        run: cd screenshot && npm install

      - name: npm install checkbox.io-micro-preview
        run: cd checkbox.io-micro-preview && npm install
      
      - name: copy mutation-coverage code
        run: cp -r /bakerx/mutation-coverage /home/vagrant/

      - name: npm install mutation-coverage code
        run: cd mutation-coverage && npm install

  - name: itrust-deploy
    deploy:
      roles:
        web:
          - sudo apt update
          - sudo apt install -y openjdk-11-jre tomcat9 git mysql-client
          - sudo ufw allow 8080/tcp
        database:
          - sudo apt update
          - sudo apt install -y mysql-server
          - sudo sed -i 's/bind-address.*=.*127.0.0.1/bind-address = 0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
          - sudo systemctl enable --now mysql
          - sudo mysql -e "CREATE USER admin@'%' IDENTIFIED BY 'admin'"
          - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO admin@'%'"
          - sudo mysql -e "FLUSH PRIVILEGES"
          - sudo ufw allow 3306/tcp
        loadbalancer:
          - sudo apt update
          - sudo apt install -y npm
          - sudo ufw allow 8080/tcp

