setup: 
  - CMD, VARIBLE, PACKAGE NAME, or DATA
  - {package: mysql, version: 8.0}
  - apt-get install mysql -y
  - java11, nodejs, wget
  - URL=https://github.ncsu.edu/engr-csc326-staff/iTrust2-v10
  - ...

jobs:
  - name: build-itrust
    steps: 
      - name: apt update
        run: sudo apt update

      - name: apt install
        run: sudo apt install -y openjdk-11-jre-headless maven mysql-server git

      - name: git clone Windows
        run: git clone https://%GITHUB_ACCESS_TOKEN%@github.ncsu.edu/engr-csc326-staff/iTrust2-v10 iTrust2

      - name: git clone Mac
        run: git clone https://${GITHUB_ACCESS_TOKEN}@github.ncsu.edu/engr-csc326-staff/iTrust2-v10 iTrust2

      - name: start mysql
        run: sudo systemctl enable --now mysql

      - name: check mysql status
        run: sudo service mysql status

      - name: create mysql account
        run: |
          'sudo mysql -e "CREATE USER admin@localhost IDENTIFIED BY ' "'"'admin'"'"'"'

      - name: check users in database
        run: |
          'sudo mysql -e "use mysql; select user,host from user"'

      - name: grant access to mysql account
        run: |
          'sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO admin@localhost"'

      - name: Flush mysql databases
        run: |
          'sudo mysql -e "FLUSH PRIVILEGES"'

      - name: create application.yml
        run: cp iTrust2/iTrust2/src/main/resources/application.yml.template iTrust2/iTrust2/src/main/resources/application.yml

      - name: update mysql username in application.yml
        run: sed -i 's/username.*/username:\ admin\/g' iTrust2/iTrust2/src/main/resources/application.yml

      - name: update mysql password in application.yml
        run: sed -i 's/password.*/password:\ admin\/g' iTrust2/iTrust2/src/main/resources/application.yml

      # - name: update mysql driver in application.yml
      #   run: sed -i 's/driver-class-name.*/driver-class-name:\ com.mysql.cj.jdbc.Driver\/g' iTrust2/iTrust2/src/main/resources/application.yml
      
      - name: print application.yml
        run: cat iTrust2/iTrust2/src/main/resources/application.yml

      - name: build iTrust2
        run: mvn -f iTrust2/iTrust2/pom.xml --batch-mode --update-snapshots clean test

  - name: mutation-coverage
    steps:
      - name: apt update
        run: sudo apt update

      - name: apt install
        run: sudo apt install -y git npm

      - name: git clone checkbox.io-micro-preview
        run: git clone https://github.com/chrisparnin/checkbox.io-micro-preview.git

      - name: git clone screenshot 
        run: git clone https://github.com/ruttabega/screenshot.git

      - name: npm install checkbox.io-micro-preview
        run: cd checkbox.io-micro-preview && npm install
      
      - name: npm install cscreenshot
        run: cd screenshot && npm install

      - name: node index.js
        run: cd checkbox.io-micro-preview && node index.js
